apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  labels: 
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: "http"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
  type: {{ .Values.service.type }}